name: 'Check spelling'
on:
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cspell and Russian dictionary
        run: |
          npm install cspell @cspell/dict-ru_ru
          
      - name: Run cspell
        run: |
          npx cspell "**/*.md" --config cspell.json --verbose --show-suggestions