name: 'Check spelling'
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: "**/*.md"
          root: '.'
          suggestions: true
          config: |
            {
              "version": "0.2",
              "language": "en,ru"
            }
          


          
